// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVKC1_9Ueu9R7F1QCFqoX83q9UDUYW02s',
    appId: '1:215436463586:web:5c133bb6f93558c9c9bdbb',
    messagingSenderId: '215436463586',
    projectId: 'flutix-5f0a5',
    authDomain: 'flutix-5f0a5.firebaseapp.com',
    storageBucket: 'flutix-5f0a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAfe-rnHMfGyipI_vxMlyCChdMO_SJdyo',
    appId: '1:215436463586:android:9a9fc19317194ae6c9bdbb',
    messagingSenderId: '215436463586',
    projectId: 'flutix-5f0a5',
    storageBucket: 'flutix-5f0a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATxP_UxfeGtqKXlvxNy1ERayZYrUq2bUo',
    appId: '1:215436463586:ios:d875718b5cc6f70dc9bdbb',
    messagingSenderId: '215436463586',
    projectId: 'flutix-5f0a5',
    storageBucket: 'flutix-5f0a5.appspot.com',
    iosClientId: '215436463586-ltvrqssg2vf5t72lsd3aum3oplno1jup.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwaFlutix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATxP_UxfeGtqKXlvxNy1ERayZYrUq2bUo',
    appId: '1:215436463586:ios:d875718b5cc6f70dc9bdbb',
    messagingSenderId: '215436463586',
    projectId: 'flutix-5f0a5',
    storageBucket: 'flutix-5f0a5.appspot.com',
    iosClientId: '215436463586-ltvrqssg2vf5t72lsd3aum3oplno1jup.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwaFlutix',
  );
}
